CREATE TABLE `IT202-User-Pokemon` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `species_name` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(50),
  `move_1` TEXT,
  `move_2` TEXT,
  `hp` SMALLINT UNSIGNED,
  `attack` SMALLINT UNSIGNED,
  `defense` SMALLINT UNSIGNED,
  `sp_attack` SMALLINT UNSIGNED,
  `sp_defense` SMALLINT UNSIGNED,
  `speed` SMALLINT UNSIGNED,
  `type_1` VARCHAR(20),
  `type_2` VARCHAR(20),
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_api` TINYINT(1) DEFAULT 1
);
